MODEL:
  TYPE: swinv2
  NAME: swinv2-benchmark 
  DROP_PATH_RATE: 0.1
  SWINV2:
    IN_CHANS: 7
    EMBED_DIM: 352
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
    NORM_PERIOD: 6
DATA:
  IMG_SIZE: 192
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  EPOCHS: 1 
  BASE_LR: 3e-4 
  MIN_LR: 1e-4
PRINT_FREQ: 128 
